// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://legora.com/
// Generated: 2026-08-23T01:33:05.298Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#0000ee' | '#005032' | '#ffffff' | '#0d1016' | '#68655e' | '#e6e6e6' | '#343434' | '#8f8d8a' | '#003d26';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'CUSTOMV2;Aktiv Grotesk VF Variable Regular' | 'Times New Roman' | 'Aktiv Grotesk VF Variable Regular';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300';

export type SpacingToken = '4px' | '20px' | '30px' | '45px' | '60px' | '80px' | '90px' | '200px' | '346px';

export type RadiusToken = '2px' | '5px' | '15px' | '24px' | '32px' | '48px' | '99px' | '999px';

export type DurationToken = '300ms' | '500ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
