// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://poolside.ai
// Generated: 2026-08-22T02:54:02.596Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#6f6d69' | '#fbfaf6' | '#93908b' | '#b3b0a9' | '#3b2c00' | '#ff5f57' | '#ffbd2e' | '#28c840' | '#0e0aff' | '#7c00fa' | '#4137ff' | '#eeede6' | '#dad9d2';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Untitled Sans' | 'Jetbrains Mono';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500';

export type SpacingToken = '1px' | '20px' | '24px' | '28px' | '32px' | '40px' | '48px' | '57px' | '76px' | '80px' | '117px' | '133px' | '196px';

export type RadiusToken = '1px' | '4px' | '10px' | '20px' | '23px' | '50px' | '9999px';

export type DurationToken = '80ms' | '100ms' | '200ms' | '300ms' | '500ms' | '1000ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
