// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://dontboardme.com/
// Generated: 2026-08-22T02:07:01.333Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#e33529' | '#0000ee' | '#693413' | '#f6f6ed' | '#2b6786' | '#ede2e2' | '#edbdd1' | '#f4ced3' | '#925026' | '#afd8fb' | '#eacdef' | '#d8b3df' | '#f0b5be' | '#ffffff' | '#5b93b0';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Times New Roman' | 'Bayon' | 'Neue Montreal' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '500' | '700';

export type SpacingToken = '1px' | '18px' | '21px' | '24px' | '28px' | '36px' | '39px' | '43px' | '50px' | '57px' | '60px' | '64px' | '76px' | '84px' | '89px' | '94px' | '101px' | '107px';

export type RadiusToken = '3px' | '9px' | '50px' | '133px' | '662px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '450ms' | '1000ms' | '1400ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
