// Framer Motion presets — generated by designlang (motionlang)
// Source: https://ishikawa.co/en/
// 2026-08-20T19:24:59.376Z
//
//   import { transitions, variants } from './ishikawa.co-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.16, 1, 0.3, 1], // 77× on page
  linear: [0, 0, 1, 1], // 3× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.08,
  xs: 0.14,
  sm: 0.16,
  md: 0.26,
  lg: 0.42,
  xl: 0.72,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.16, ease: easings.easeOut },
  fast:  { duration: 0.100, ease: easings.easeOut },
  slow:  { duration: 0.288, ease: easings.easeOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.040 } },
  },
  gameBootLogoBreathe: {
    hidden: {},
    show: {
      "opacity": ["0.66","0.78"],
      "transform": ["translate3d(0, var(--game-boot-logo-offset-y), 0) scale(0.995)","translate3d(0, var(--game-boot-logo-offset-y), 0) scale(1.008)"],
      transition: transitions.base,
    },
  },
  journeyHubThresholdBreathe: {
    hidden: {},
    show: {
      "opacity": ["0.34","0.92"],
      "transform": ["translateY(0px)","translateY(-2px)"],
      transition: transitions.base,
    },
  },
  worldCursorBreathe: {
    hidden: {},
    show: {
      "opacity": ["0.24","0.58"],
      "transform": ["scale(0.86) rotate(-4deg)","scale(1.08) rotate(7deg)"],
      transition: transitions.base,
    },
  },
  worldCursorMote: {
    hidden: {},
    show: {
      "opacity": ["0.28","0.82"],
      transition: transitions.base,
    },
  },
  journeySpaceThink: {
    hidden: {},
    show: {
      "opacity": ["0.28","0.9"],
      "transform": ["translateY(3px) scale(0.78)","translateY(-3px) scale(1.08)"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
