// Web Animations API presets — generated by designlang (motionlang)
// Source: https://ishikawa.co/en/
// 2026-08-20T19:24:59.379Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './ishikawa.co-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeOut: 'cubic-bezier(0.16, 1, 0.3, 1)', // 77× on page
  linear: 'linear', // 3× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  instant: 80,
  xs: 140,
  sm: 160,
  md: 260,
  lg: 420,
  xl: 720,
};

/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */
export const keyframes = {
  gameBootLogoBreathe: [{"opacity":"0.66","transform":"translate3d(0, var(--game-boot-logo-offset-y), 0) scale(0.995)","offset":0},{"opacity":"0.78","transform":"translate3d(0, var(--game-boot-logo-offset-y), 0) scale(1.008)","offset":1}],
  journeyHubThresholdBreathe: [{"opacity":"0.34","transform":"translateY(0px)","offset":0},{"opacity":"0.92","transform":"translateY(-2px)","offset":1}],
  worldCursorBreathe: [{"opacity":"0.24","transform":"scale(0.86) rotate(-4deg)","offset":0},{"opacity":"0.58","transform":"scale(1.08) rotate(7deg)","offset":1}],
  worldCursorMote: [{"opacity":"0.28","offset":0},{"opacity":"0.82","offset":1}],
  journeySpaceThink: [{"opacity":"0.28","transform":"translateY(3px) scale(0.78)","offset":0},{"opacity":"0.9","transform":"translateY(-3px) scale(1.08)","offset":1}],
  atlasScrollParticle: [{"opacity":"0","transform":"translate(-50%, 0px) scale(0.7)","offset":0},{"opacity":"0.8","offset":0.28},{"opacity":"0.38","offset":0.78},{"opacity":"0","transform":"translate(-50%, 34px) scale(1.15)","offset":1}],
};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 160, easing: easings.easeOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
