// GSAP presets — generated by designlang (motionlang)
// Source: https://ishikawa.co/en/
// 2026-08-20T19:24:59.379Z
//
//   import gsap from 'gsap';
//   import { registerEases, reveals } from './ishikawa.co-motion.gsap.js';
//   registerEases(gsap);            // one-time: registers CustomEases
//   reveals.slideUp('.card');

/** CustomEase path data extracted from the live page, keyed by family. */
export const eases = {
  easeOut: 'M0,0 C0.16,1 0.3,1 1,1', // 77× on page
  linear: 'M0,0 C0,0 1,1 1,1', // 3× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.08,
  xs: 0.14,
  sm: 0.16,
  md: 0.26,
  lg: 0.42,
  xl: 0.72,
};

/** Register every extracted curve as a named GSAP CustomEase. Call once. */
export function registerEases(gsap) {
  const CustomEase = gsap.plugins?.CustomEase || (typeof window !== 'undefined' && window.CustomEase);
  if (!CustomEase) {
    console.warn('[motion.gsap] CustomEase plugin not registered — call gsap.registerPlugin(CustomEase) first.');
    return;
  }
  for (const [name, path] of Object.entries(eases)) CustomEase.create(name, path);
}

/** gsap.from() reveal helpers. Pass any GSAP target + optional vars override. */
export const reveals = {
  fadeIn: (target, vars = {}) => gsap.from(target, { opacity: 0, duration: 0.16, ease: 'easeOut', ...vars }),
  slideUp: (target, vars = {}) => gsap.from(target, { opacity: 0, y: 24, duration: 0.16, ease: 'easeOut', ...vars }),
  slideDown: (target, vars = {}) => gsap.from(target, { opacity: 0, y: -24, duration: 0.16, ease: 'easeOut', ...vars }),
  scaleIn: (target, vars = {}) => gsap.from(target, { opacity: 0, scale: 0.96, duration: 0.16, ease: 'easeOut', ...vars }),
  pop: (target, vars = {}) => gsap.from(target, { scale: 0.9, duration: 0.16, ease: 'easeOut', ...vars }),
};

/** Site uses scroll-/view-timeline. Batch-reveals elements as they enter. */
/** Requires: gsap.registerPlugin(ScrollTrigger). */
export function revealOnScroll(targets, vars = {}) {
  return gsap.utils.toArray(targets).map((el) =>
    gsap.from(el, {
      opacity: 0, y: 24, duration: 0.16, ease: 'easeOut', ...vars,
      scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none reverse' },
    }));
}

export default { eases, durations, registerEases, reveals };
