// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://ishikawa.co/en/
// Generated: 2026-08-20T19:24:59.373Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#1f1f1f' | '#333735' | '#2f302d' | '#000000' | '#486c62' | '#ffffff' | '#bcc268' | '#5b8b70' | '#dcf6f2' | '#ebe8c1' | '#444444' | '#30654a' | '#4ee8dd' | '#50a4b4' | '#924437' | '#914652' | '#7e561c' | '#423737' | '#d45199' | '#30443d' | '#62aabe' | '#d5809b' | '#696b74' | '#cea02e' | '#101010' | '#5c9788' | '#4a8a94' | '#744d80' | '#bf9225' | '#3e5c52' | '#be747b' | '#f0f0f0' | '#60626c' | '#d7da8e' | '#34534a' | '#5c4d23' | '#140a1b' | '#b8873f' | '#5a96a5' | '#767676' | '#bf914b';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Avenir Next' | 'Ishikawa Klee' | 'Times New Roman' | 'Helvetica Neue' | 'SF Mono' | 'Arial';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '600' | '500' | '700' | '620';

export type SpacingToken = '1px' | '42px' | '52px' | '56px' | '64px' | '72px' | '96px' | '130px' | '180px';

export type RadiusToken = '1px' | '6px' | '50px' | '53px' | '56px' | '70px' | '999px';

export type DurationToken = '80ms' | '140ms' | '160ms' | '260ms' | '420ms' | '720ms';
export type EasingToken   = never;

export type MaterialLanguage = 'material-you';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
