// Motion One presets — generated by designlang (motionlang)
// Source: https://ishikawa.co/en/
// 2026-08-20T19:24:59.377Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './ishikawa.co-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  easeOut: [0.16, 1, 0.3, 1], // 77× on page
  linear: [0, 0, 1, 1], // 3× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.08,
  xs: 0.14,
  sm: 0.16,
  md: 0.26,
  lg: 0.42,
  xl: 0.72,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** @keyframes blocks reconstructed as Motion One keyframe maps. */
export const keyframes = {
  gameBootLogoBreathe: {
    "opacity": ["0.66","0.78"],
    "transform": ["translate3d(0, var(--game-boot-logo-offset-y), 0) scale(0.995)","translate3d(0, var(--game-boot-logo-offset-y), 0) scale(1.008)"]
  },
  journeyHubThresholdBreathe: {
    "opacity": ["0.34","0.92"],
    "transform": ["translateY(0px)","translateY(-2px)"]
  },
  worldCursorBreathe: {
    "opacity": ["0.24","0.58"],
    "transform": ["scale(0.86) rotate(-4deg)","scale(1.08) rotate(7deg)"]
  },
  worldCursorMote: {
    "opacity": ["0.28","0.82"]
  },
  journeySpaceThink: {
    "opacity": ["0.28","0.9"],
    "transform": ["translateY(3px) scale(0.78)","translateY(-3px) scale(1.08)"]
  },
  atlasScrollParticle: {
    "opacity": ["0","0.8","0.38","0"],
    "transform": ["translate(-50%, 0px) scale(0.7)","translate(-50%, 34px) scale(1.15)"]
  },
};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.16, easing: easings.easeOut };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
