// Web Animations API presets — generated by designlang (motionlang)
// Source: https://stripe.com
// 2026-08-22T02:46:33.946Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './stripe.com-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeOut: 'cubic-bezier(0.25, 1, 0.5, 1)', // 478× on page
  linear: 'linear', // 45× on page
  custom5: 'cubic-bezier(0.3, 0, 0.2, 1)', // 16× on page
  custom6: 'cubic-bezier(0.45, 0.05, 0.55, 0.95)', // 13× on page
  custom7: 'cubic-bezier(0.65, 0, 0.35, 1)', // 13× on page
  custom10: 'cubic-bezier(0.6, 0, 0.2, 0.5)', // 8× on page
  easeInOut: 'ease', // 6× on page
  custom12: 'cubic-bezier(0.4, 0, 0.2, 1)', // 3× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  xs: 100,
  sm: 200,
  md: 300,
  lg: 500,
  xl: 800,
};

/** No on-page @keyframes were attached to elements; emit empty for shape parity. */
export const keyframes = {};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 300, easing: easings.easeOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
