// GSAP presets — generated by designlang (motionlang)
// Source: https://stripe.com
// 2026-08-22T02:46:33.945Z
//
//   import gsap from 'gsap';
//   import { registerEases, reveals } from './stripe.com-motion.gsap.js';
//   registerEases(gsap);            // one-time: registers CustomEases
//   reveals.slideUp('.card');

/** CustomEase path data extracted from the live page, keyed by family. */
export const eases = {
  easeOut: 'M0,0 C0.25,1 0.5,1 1,1', // 478× on page
  linear: 'M0,0 C0,0 1,1 1,1', // 45× on page
  custom5: 'M0,0 C0.3,0 0.2,1 1,1', // 16× on page
  custom6: 'M0,0 C0.45,0.05 0.55,0.95 1,1', // 13× on page
  custom7: 'M0,0 C0.65,0 0.35,1 1,1', // 13× on page
  custom10: 'M0,0 C0.6,0 0.2,0.5 1,1', // 8× on page
  easeInOut: 'M0,0 C0.25,0.1 0.25,1 1,1', // 6× on page
  custom12: 'M0,0 C0.4,0 0.2,1 1,1', // 3× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
  lg: 0.5,
  xl: 0.8,
};

/** Register every extracted curve as a named GSAP CustomEase. Call once. */
export function registerEases(gsap) {
  const CustomEase = gsap.plugins?.CustomEase || (typeof window !== 'undefined' && window.CustomEase);
  if (!CustomEase) {
    console.warn('[motion.gsap] CustomEase plugin not registered — call gsap.registerPlugin(CustomEase) first.');
    return;
  }
  for (const [name, path] of Object.entries(eases)) CustomEase.create(name, path);
}

/** gsap.from() reveal helpers. Pass any GSAP target + optional vars override. */
export const reveals = {
  fadeIn: (target, vars = {}) => gsap.from(target, { opacity: 0, duration: 0.3, ease: 'easeOut', ...vars }),
  slideUp: (target, vars = {}) => gsap.from(target, { opacity: 0, y: 24, duration: 0.3, ease: 'easeOut', ...vars }),
  slideDown: (target, vars = {}) => gsap.from(target, { opacity: 0, y: -24, duration: 0.3, ease: 'easeOut', ...vars }),
  scaleIn: (target, vars = {}) => gsap.from(target, { opacity: 0, scale: 0.96, duration: 0.3, ease: 'easeOut', ...vars }),
  pop: (target, vars = {}) => gsap.from(target, { scale: 0.9, duration: 0.3, ease: 'easeOut', ...vars }),
  stagger: (targets, vars = {}) => gsap.from(targets, { opacity: 0, y: 24, duration: 0.3, ease: 'easeOut', stagger: 0.080, ...vars }),
};

/** Site uses scroll-/view-timeline. Batch-reveals elements as they enter. */
/** Requires: gsap.registerPlugin(ScrollTrigger). */
export function revealOnScroll(targets, vars = {}) {
  return gsap.utils.toArray(targets).map((el) =>
    gsap.from(el, {
      opacity: 0, y: 24, duration: 0.3, ease: 'easeOut', ...vars,
      scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none reverse' },
    }));
}

export default { eases, durations, registerEases, reveals };
