// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://austinwerner.io/
// Generated: 2026-08-20T19:31:53.213Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#ffffff' | '#939393' | '#1b1b1b' | '#484848' | '#2d4156' | '#d9b915' | '#9e9e9e' | '#aaaaaa' | '#e9edf2' | '#292929' | '#ffd100' | '#ff6d36' | '#2bc6d9' | '#171717';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Times New Roman' | 'Sofia Pro' | 'Space Grotesk' | 'Arial' | 'Neue Machina' | 'Strawford';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '600';

export type SpacingToken = '5px' | '39px' | '46px' | '55px' | '60px' | '66px' | '70px' | '75px' | '80px' | '84px' | '90px' | '97px' | '100px' | '120px' | '253px' | '265px' | '272px';

export type RadiusToken = '3px' | '6px' | '50px' | '54px' | '64px' | '100px';

export type DurationToken = '150ms' | '250ms' | '300ms' | '500ms' | '800ms' | '1300ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
