// Framer Motion presets — generated by designlang (motionlang)
// Source: https://www.memphispolice.org/about/
// 2026-08-20T16:25:37.720Z
//
//   import { transitions, variants } from './memphispolice.org-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeInOut: [0.25, 0.1, 0.25, 1], // 4× on page
  linear: [0, 0, 1, 1], // 4× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.15,
  sm: 0.2,
  md: 0.3,
  lg: 0.42,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.3, ease: easings.easeInOut },
  fast:  { duration: 0.150, ease: easings.easeInOut },
  slow:  { duration: 0.540, ease: easings.easeInOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.075 } },
  },
  ukSpinnerRotate: {
    hidden: {},
    show: {
      "transform": ["rotate(0deg)","rotate(270deg)"],
      transition: transitions.base,
    },
  },
  ukSpinnerDash: {
    hidden: {},
    show: {
      "strokeDashoffset": ["88px","22px","88px"],
      "transform": ["rotate(135deg)","rotate(450deg)"],
      transition: transitions.base,
    },
  },
  ukFade: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      transition: transitions.base,
    },
  },
  ukFadeBottomMedium: {
    hidden: {},
    show: {
      "opacity": ["0","1"],
      "transform": ["translateY(50px)","translateY(0px)"],
      transition: transitions.base,
    },
  },
  slideInUp: {
    hidden: {},
    show: {
      "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"],
      transition: transitions.base,
    },
  },
  slideInUp: {
    hidden: {},
    show: {
      "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"],
      transition: transitions.base,
    },
  },
  slideInUp: {
    hidden: {},
    show: {
      "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"],
      transition: transitions.base,
    },
  },
  slideInUp: {
    hidden: {},
    show: {
      "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"],
      transition: transitions.base,
    },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
