// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.memphispolice.org/about/
// Generated: 2026-08-20T16:25:37.718Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#3a3a3a' | '#ffffff' | '#191919' | '#666666' | '#e0e0e0' | '#0d2279' | '#2d2f94' | '#1e73be' | '#0094ea' | '#004276' | '#000000' | '#fcac00' | '#adb5b7' | '#dd4f3d' | '#808080' | '#0866ff' | '#1da1f2' | '#ff0000' | '#e23367' | '#9b9b9b' | '#1a65a7' | '#f0f0f0';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'Lato' | 'Merriweather Sans' | 'Arial' | 'Hind' | 'vote-reward-badges';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '700';

export type SpacingToken = '1px' | '15px' | '26px' | '30px' | '35px' | '40px' | '50px' | '60px' | '70px' | '240px';

export type RadiusToken = '50px';

export type DurationToken = '150ms' | '200ms' | '300ms' | '420ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
