// Motion One presets — generated by designlang (motionlang)
// Source: https://www.memphispolice.org/about/
// 2026-08-20T16:25:37.722Z
//
//   import { animate } from 'motion';
//   import { animations, easings, durations } from './memphispolice.org-motion.one.js';
//
//   animations.fadeIn('#hero');
//   animations.slideUp('.card', { delay: 0.1 });

/** Easing curves extracted from the live page, as Motion One cubic-bezier arrays. */
export const easings = {
  easeInOut: [0.25, 0.1, 0.25, 1], // 4× on page
  linear: [0, 0, 1, 1], // 4× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.15,
  sm: 0.2,
  md: 0.3,
  lg: 0.42,
};

/** Motion One spring options — pass as the `type: 'spring'` block of an animate() call. */
export const springs = {
  soft: { type: 'spring', stiffness: 320, damping: 30, mass: 1 },
};

/** @keyframes blocks reconstructed as Motion One keyframe maps. */
export const keyframes = {
  ukSpinnerRotate: {
    "transform": ["rotate(0deg)","rotate(270deg)"]
  },
  ukSpinnerDash: {
    "strokeDashoffset": ["88px","22px","88px"],
    "transform": ["rotate(135deg)","rotate(450deg)"]
  },
  ukFade: {
    "opacity": ["0","1"]
  },
  ukFadeBottomMedium: {
    "opacity": ["0","1"],
    "transform": ["translateY(50px)","translateY(0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
  slideInUp: {
    "transform": ["translate3d(0px, 100%, 0px)","translate3d(0px, 0px, 0px)"]
  },
};

/** Animate-on-call helpers. Each takes a Motion One target + optional override. */
import { animate } from 'motion';

const _t = { duration: 0.3, easing: easings.easeInOut };

export const animations = {
  fadeIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1] }, { ..._t, ...opts }),
  fadeOut: (target, opts = {}) =>
    animate(target, { opacity: [1, 0] }, { ..._t, ...opts }),
  slideUp: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [16, 0] }, { ..._t, ...opts }),
  slideDown: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], y: [-16, 0] }, { ..._t, ...opts }),
  scaleIn: (target, opts = {}) =>
    animate(target, { opacity: [0, 1], scale: [0.96, 1] }, { ..._t, ...opts }),
  pop: (target, opts = {}) =>
    animate(target, { scale: [0.9, 1] }, { ...springs.soft, ...opts }),
};

/** Site uses scroll- or view-timeline. Helpers wired to Motion One's `inView` / `scroll`. */
import { inView, scroll } from 'motion';

export const enterOnView = (target, variant = animations.slideUp) =>
  inView(target, (el) => { variant(el.target); });

export const parallaxY = (target, distance = 80) =>
  scroll(animate(target, { y: [0, -distance] }, { easing: 'linear' }));

export default { easings, durations, springs, keyframes, animations };
