// Web Animations API presets — generated by designlang (motionlang)
// Source: https://www.memphispolice.org/about/
// 2026-08-20T16:25:37.724Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './memphispolice.org-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeInOut: 'ease', // 4× on page
  linear: 'linear', // 4× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  xs: 150,
  sm: 200,
  md: 300,
  lg: 420,
};

/** @keyframes blocks reconstructed as WAAPI keyframe arrays. */
export const keyframes = {
  ukSpinnerRotate: [{"transform":"rotate(0deg)","offset":0},{"transform":"rotate(270deg)","offset":1}],
  ukSpinnerDash: [{"strokeDashoffset":"88px","offset":0},{"strokeDashoffset":"22px","transform":"rotate(135deg)","offset":0.5},{"strokeDashoffset":"88px","transform":"rotate(450deg)","offset":1}],
  ukFade: [{"opacity":"0","offset":0},{"opacity":"1","offset":1}],
  ukFadeBottomMedium: [{"opacity":"0","transform":"translateY(50px)","offset":0},{"opacity":"1","transform":"translateY(0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
  slideInUp: [{"transform":"translate3d(0px, 100%, 0px)","visibility":"visible","offset":0},{"transform":"translate3d(0px, 0px, 0px)","offset":1}],
};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 300, easing: easings.easeInOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
