// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://www.roberttran.com.au/
// Generated: 2026-08-22T02:59:54.851Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#16140f' | '#45413a' | '#000000' | '#f4f1e9' | '#a6382c' | '#e7e0d0' | '#fbfaf5' | '#ccbe9f' | '#c9503f';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'caslonText' | 'franklin' | 'jetbrainsMono' | 'caslonDisplay';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '700' | '500' | '600' | '900' | '800';

export type SpacingToken = '2px' | '48px' | '56px' | '76px' | '138px';

export type RadiusToken = '7px' | '50px';

export type DurationToken = '40ms' | '100ms' | '160ms' | '260ms' | '410ms';
export type EasingToken   = never;

export type MaterialLanguage = 'flat';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
