// Web Animations API presets — generated by designlang (motionlang)
// Source: https://www.roberttran.com.au/
// 2026-08-22T02:59:54.854Z
//
// Zero-dependency. Runs on the browser-native Element.animate().
//   import { animations } from './roberttran.com.au-motion.waapi.js';
//   animations.fadeIn(document.querySelector('#hero'));
//   await animations.slideUp(card, { delay: 80 }).finished;

/** Easing curves extracted from the live page, as WAAPI easing strings. */
export const easings = {
  easeOut: 'cubic-bezier(0.22, 1, 0.36, 1)', // 44× on page
  easeInOut: 'ease', // 42× on page
  custom3: 'cubic-bezier(0.4, 0, 0.2, 1)', // 34× on page
  spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)', // 13× on page
};

/** Duration presets (milliseconds), extracted from the live page. */
export const durations = {
  instant: 40,
  xs: 100,
  sm: 160,
  md: 260,
  lg: 410,
};

/** No on-page @keyframes were attached to elements; emit empty for shape parity. */
export const keyframes = {};

/** Honours the user's reduced-motion preference. */
export const prefersReducedMotion = () =>
  typeof matchMedia === 'function' && matchMedia('(prefers-reduced-motion: reduce)').matches;

const _timing = { duration: 160, easing: easings.easeOut, fill: 'both' };

function _animate(el, frames, opts = {}) {
  const timing = { ..._timing, ...opts };
  if (prefersReducedMotion()) timing.duration = 0;
  return el.animate(frames, timing);
}

/** Animate-on-call helpers. Each returns the live Animation (await `.finished`). */
export const animations = {
  fadeIn: (el, opts = {}) => _animate(el, [{ opacity: 0 }, { opacity: 1 }], opts),
  fadeOut: (el, opts = {}) => _animate(el, [{ opacity: 1 }, { opacity: 0 }], opts),
  slideUp: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  slideDown: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'translateY(-16px)' }, { opacity: 1, transform: 'translateY(0)' }], opts),
  scaleIn: (el, opts = {}) => _animate(el, [{ opacity: 0, transform: 'scale(0.96)' }, { opacity: 1, transform: 'scale(1)' }], opts),
};

export default { easings, durations, keyframes, animations, prefersReducedMotion };
