// GSAP presets — generated by designlang (motionlang)
// Source: https://www.roberttran.com.au/
// 2026-08-22T02:59:54.853Z
//
//   import gsap from 'gsap';
//   import { registerEases, reveals } from './roberttran.com.au-motion.gsap.js';
//   registerEases(gsap);            // one-time: registers CustomEases
//   reveals.slideUp('.card');

/** CustomEase path data extracted from the live page, keyed by family. */
export const eases = {
  easeOut: 'M0,0 C0.22,1 0.36,1 1,1', // 44× on page
  easeInOut: 'M0,0 C0.25,0.1 0.25,1 1,1', // 42× on page
  custom3: 'M0,0 C0.4,0 0.2,1 1,1', // 34× on page
  spring: 'M0,0 C0.34,1.56 0.64,1 1,1', // 13× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.04,
  xs: 0.1,
  sm: 0.16,
  md: 0.26,
  lg: 0.41,
};

/** Register every extracted curve as a named GSAP CustomEase. Call once. */
export function registerEases(gsap) {
  const CustomEase = gsap.plugins?.CustomEase || (typeof window !== 'undefined' && window.CustomEase);
  if (!CustomEase) {
    console.warn('[motion.gsap] CustomEase plugin not registered — call gsap.registerPlugin(CustomEase) first.');
    return;
  }
  for (const [name, path] of Object.entries(eases)) CustomEase.create(name, path);
}

/** gsap.from() reveal helpers. Pass any GSAP target + optional vars override. */
export const reveals = {
  fadeIn: (target, vars = {}) => gsap.from(target, { opacity: 0, duration: 0.16, ease: 'easeOut', ...vars }),
  slideUp: (target, vars = {}) => gsap.from(target, { opacity: 0, y: 24, duration: 0.16, ease: 'easeOut', ...vars }),
  slideDown: (target, vars = {}) => gsap.from(target, { opacity: 0, y: -24, duration: 0.16, ease: 'easeOut', ...vars }),
  scaleIn: (target, vars = {}) => gsap.from(target, { opacity: 0, scale: 0.96, duration: 0.16, ease: 'easeOut', ...vars }),
  pop: (target, vars = {}) => gsap.from(target, { scale: 0.9, duration: 0.16, ease: 'spring', ...vars }),
  stagger: (targets, vars = {}) => gsap.from(targets, { opacity: 0, y: 24, duration: 0.16, ease: 'easeOut', stagger: 0.080, ...vars }),
};

/** Site uses scroll-/view-timeline. Batch-reveals elements as they enter. */
/** Requires: gsap.registerPlugin(ScrollTrigger). */
export function revealOnScroll(targets, vars = {}) {
  return gsap.utils.toArray(targets).map((el) =>
    gsap.from(el, {
      opacity: 0, y: 24, duration: 0.16, ease: 'easeOut', ...vars,
      scrollTrigger: { trigger: el, start: 'top 85%', toggleActions: 'play none none reverse' },
    }));
}

export default { eases, durations, registerEases, reveals };
