// Framer Motion presets — generated by designlang (motionlang)
// Source: https://www.roberttran.com.au/
// 2026-08-22T02:59:54.852Z
//
//   import { transitions, variants } from './roberttran.com.au-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.22, 1, 0.36, 1], // 44× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 42× on page
  custom3: [0.4, 0, 0.2, 1], // 34× on page
  spring: [0.34, 1.56, 0.64, 1], // 13× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  instant: 0.04,
  xs: 0.1,
  sm: 0.16,
  md: 0.26,
  lg: 0.41,
};

/** Spring presets — pass to a Framer Motion `transition` prop. */
export const springs = {
  soft: { type: 'spring', stiffness: 700, damping: 8, mass: 1 },
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.16, ease: easings.easeOut },
  fast:  { duration: 0.100, ease: easings.easeOut },
  slow:  { duration: 0.288, ease: easings.easeOut },
  spring: springs.soft,
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  pop: {
    hidden: { opacity: 0, scale: 0.9 },
    show:   { opacity: 1, scale: 1, transition: springs.soft },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.040 } },
  },
};

/** Site uses scroll- or view-timeline. Drop-in `whileInView` props. */
export const inView = {
  fadeIn: {
    initial: variants.fade.hidden,
    whileInView: variants.fade.show,
    viewport: { once: true, amount: 0.3 },
  },
  riseIn: {
    initial: variants.slideUp.hidden,
    whileInView: variants.slideUp.show,
    viewport: { once: true, amount: 0.3 },
  },
};

export default { easings, durations, springs, transitions, variants, inView };
